rqworker:
  build: .
  links:
    - rqredis
  command: rqworker -u redis://rqredis:6379/
rqdashboard:
  image: rq-dashboard:latest
  ports:
    - 9181:9181
  links:
    - rqredis
  command: rq-dashboard -H rqredis
rqredis:
  image: redis:2.8
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"
