name: desertpy_2016-12-26_v1
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- alabaster=0.7.9=py35_0
- anaconda-client=1.6.0=py35_0
- anaconda=custom=py35_0
- appnope=0.1.0=py35_0
- astroid=1.4.7=py35_0
- babel=2.3.4=py35_0
- blaze=0.10.1=py35_0
- bokeh=0.12.3=py35_0
- chest=0.2.3=py35_0
- click=6.6=py35_0
- cloudpickle=0.2.1=py35_0
- clyent=1.2.2=py35_0
- cycler=0.10.0=py35_0
- cytoolz=0.8.2=py35_0
- dask=0.12.0=py35_0
- datashape=0.5.3=py35_0
- decorator=4.0.10=py35_1
- docutils=0.12=py35_2
- entrypoints=0.2.2=py35_0
- flask=0.12=py35_0
- flask-cors=2.1.2=py35_0
- freetype=2.5.5=1
- h5py=2.6.0=np111py35_2
- hdf5=1.8.17=1
- heapdict=1.0.0=py35_1
- icu=54.1=0
- imagesize=0.7.1=py35_0
- ipykernel=4.5.2=py35_0
- ipython=5.1.0=py35_1
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- itsdangerous=0.24=py35_0
- jbig=2.1=0
- jedi=0.9.0=py35_1
- jinja2=2.8=py35_1
- jpeg=8d=2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.1=py35_0
- lazy-object-proxy=1.2.1=py35_0
- libpng=1.6.22=0
- libtiff=4.0.6=2
- llvmlite=0.15.0=py35_0
- locket=0.2.0=py35_1
- markupsafe=0.23=py35_2
- matplotlib=1.5.3=np111py35_1
- mistune=0.7.3=py35_1
- mkl=11.3.3=0
- mpmath=0.19=py35_1
- multipledispatch=0.4.9=py35_0
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.2.0=py35_0
- nbpresent=3.0.2=py35_0
- networkx=1.11=py35_0
- notebook=4.3.0=py35_0
- numba=0.30.0=np111py35_0
- numexpr=2.6.1=np111py35_1
- numpy=1.11.2=py35_0
- odo=0.5.0=py35_1
- openssl=1.0.2j=0
- pandas=0.19.1=np111py35_0
- partd=0.3.6=py35_0
- path.py=8.2.1=py35_0
- patsy=0.4.1=py35_0
- pep8=1.7.0=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=3.4.2=py35_0
- pip=9.0.1=py35_1
- prompt_toolkit=1.0.9=py35_0
- psutil=5.0.1=py35_0
- ptyprocess=0.5.1=py35_0
- pyflakes=1.3.0=py35_0
- pygments=2.1.3=py35_0
- pylint=1.5.4=py35_1
- pyparsing=2.1.4=py35_0
- pyqt=5.6.0=py35_1
- pytables=3.3.0=np111py35_0
- python=3.5.2=0
- python-dateutil=2.6.0=py35_0
- python.app=1.2=py35_4
- pytz=2016.10=py35_0
- pyyaml=3.12=py35_0
- pyzmq=16.0.2=py35_0
- qt=5.6.2=0
- qtawesome=0.3.3=py35_0
- qtconsole=4.2.1=py35_1
- qtpy=1.1.2=py35_0
- readline=6.2=2
- requests=2.12.4=py35_0
- rope=0.9.4=py35_1
- scikit-image=0.12.3=np111py35_1
- scikit-learn=0.18.1=np111py35_0
- scipy=0.18.1=np111py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.5.1=py35_0
- spyder=3.0.2=py35_0
- sqlalchemy=1.1.4=py35_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py35_1
- sympy=1.0=py35_0
- terminado=0.6=py35_0
- tk=8.5.18=0
- toolz=0.8.2=py35_0
- tornado=4.4.2=py35_0
- traitlets=4.3.1=py35_0
- wcwidth=0.1.7=py35_0
- werkzeug=0.11.11=py35_1
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- wrapt=1.10.8=py35_0
- xz=5.2.2=0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.9
  - rope-py3k==0.9.4.post1
  - tables==3.3.0

